# SPDX-FileCopyrightText: Copyright (c) 2017-2023 slowtec GmbH <post@slowtec.de>
# SPDX-License-Identifier: CC0-1.0

overrides:
  - files:
      - "**/*.yaml"
    options:
      tabWidth: 2
      # in double quotes you can use escapes
      singleQuote: false
  - files:
      - "**/*.md"
    options:
      printWidth: 80
      proseWrap: always
